###
POST http://localhost:8090/trips
Content-Type: application/json

{
  "description": "Trip to Mexico",
  "shortDescription": "Mexico trip",
  "destination": "Mexico",
  "seatsNumber": 3,
  "tripCode": "101"
}

###
POST http://localhost:8090/reservations
Content-Type: application/json

{
  "tripCode": "101",
  "userId": "kazik"
}
